# Copyright (c) 2026 Cromulence
services:
  server:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.server
    container_name: server
    ports:
      - "5000:5000"
    networks:
      - png-network

  poller:
    build:
      context: .
      dockerfile: poller/Dockerfile.poller
    container_name: poller
    networks:
      - png-network
    environment:
      HOST: server
      PORT: 5000
      SNAPSHOT: false

  pov:
    build:
      context: .
      dockerfile: pov/Dockerfile.pov
    container_name: pov
    networks:
      - png-network
    environment:
      HOST: server
      PORT: 5000

networks:
  png-network:
